### ISSUE TITLE
拓展uni-icons 的第三方 图标类型

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-ui-types#31]
### 对问题的清晰和简明的描述

# uni-icons 时使用 自定义图标时 type 类型报错

```vue
  <uni-icons custom-prefix="iconfont" size="40" :color="COLOR_PRIMARY" type="icon-search" /> //不能将类型“"icon-search"”分配给类型“_UniIconsType | undefined”。
```

### 推荐的解决方案

修改 uni-icons的props
```ts

// index.d.ts
_UniIconsProps {
... 
/**
   * 图标图案
   *
   * 默认为 空字符串
   */
  type: _UniIconsType | `icon-${string}`;

}
```

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
已经补充，包含在 v0.5.1 中，请尝试 :D

**Comment by zhuddan** [comment]
> 已经补充，包含在 v0.5.1 中，请尝试 :D

谢谢！！！
