### ISSUE TITLE
uni-fab props vertical 类型错误

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-ui-types#34]
### 描述问题

`uni-fab`的垂直对其属性`vertical`类型应该是上对齐(top)或者下对齐(bottom) 而不是`type _UniFabVertical = 'bottom' | 'right';`
参考

[uni-ni 官网](https://zh.uniapp.dcloud.io/component/uniui/uni-fav.html#fav-props)
[uni-ui-type 源代码](https://github.com/uni-helper/uni-ui-types/blob/main/src/UniFab.ts#L46)

### 复现

```vue
  <uni-fab vertical="top" /> //不能将类型“"top"”分配给类型“_UniFabVertical | undefined”。
```

建议
```ts
type _UniFabVertical = 'bottom' | 'top';
```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 5.29 GB / 15.73 GB
  Binaries:
    Node: 14.21.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 6.14.18 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54), ChromiumDev (112.0.1722.23)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
🙏万分感谢指出这个问题！已经发布了 0.5.3，请尝试 :D

**Comment by zhuddan** [comment]
> 🙏万分感谢指出这个问题！已经发布了 0.5.3，请尝试 :D

没有，我才应该谢谢你🙏
