### ISSUE TITLE
uni-file-picker 的 onSuccess 中的返回参数_UniFilePickerOnSuccessEvent的tempFiles类型可能不正确

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-ui-types#35]
### 描述问题

首先我不确认这是否是一个bug(毕竟uni-ui官方也他妈描述的不清晰)，有点强行，只是我自定义上传时候`onSelect`拿到的tempFiles以为是文件列表，但确实是包含文件信息的对象列表，导致我上传到服务器失败，我应该上传`tempFiles[0].file`，才可以正常上传，导致我ts项目中类型错误。

根据[uni-file-picker官方文档](https://zh.uniapp.dcloud.io/component/uniui/uni-file-picker.html#callback-params) 中的描述`tempFiles`的类型为`files`, 即文件列表,包含文件流，文件大小，文件名称等。从这里看出来并不是内置的`File`类型。另外从[uni-file-picker 源码](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue#L481)的`this.$emit('success'...)` 中的[backObject 方法](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue#L575)，我推测出tempFiles类型应该为
```ts
interface TempFile {
  file: File; // 上传的文件
  name: string; // 文件名
  uuid: number; // 文件uuid
  extname: string; // 文件扩展名
  cloudPath: string; // uniCloud 上传地址
  fileType: string; // 文件类型
  url: string; // 本地 blob 地址
  size: number; // 文件大小
  path: string; // 文件地址
  video: Record<string, any>;// 视频文件信息  这个真不知道是返回了啥 ，下文中的image也可以笼统写为Record<string, any>
  image: { // 图片文件信息
    width: number;
    height: number;
    location: string;
  };
  progress: number; // 上传进度
  status: string; // 状态
}

```
下文是我实际项目中`onSelect`方法的截图
![image](https://user-images.githubusercontent.com/32126992/229029996-7847b349-2d93-4d82-b530-62f068bce835.png)

其他，在uni-ui官方的文档上我也已经提了[Update uni-file-picker.md](https://gitcode.net/dcloud/unidocs-zh/-/merge_requests/106/commits)

最后，如果确实不能算作个bug, 给您带来了困惑,麻烦及时联系我

### 复现

```ts
function onUploadFile(tempFiles: UploadFileType['tempFiles']) {
  console.log(tempFiles[0]);
  uni.uploadFile({
    url: `${__APP_API_URL__}/common/uploadMinio`,
    file: tempFiles[0].file, // 类型“File”上不存在属性“file”
    // file: tempFiles[0],
    name: 'file',
    header: {
      Authorization: `Bearer ${getToken()}`,
    },
  }).then((res) => {
    console.log(res);
    if (res.statusCode != 200) {
      //
    }
  });
}
```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 4.09 GB / 15.73 GB
  Binaries:
    Node: 14.21.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 6.14.18 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54), ChromiumDev (112.0.1722.23)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
我看了一下 https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue#L399-L415，发现确实是文档对不上代码。

我觉得还是以实际表现为准，我尽快核对一下 `uni-file-picker` 返回的参数。

**Comment by zhuddan** [comment]
> 我看了一下 [https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue#L399-L415，发现确实是文档对不上代码。](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue#L399-L415%EF%BC%8C%E5%8F%91%E7%8E%B0%E7%A1%AE%E5%AE%9E%E6%98%AF%E6%96%87%E6%A1%A3%E5%AF%B9%E4%B8%8D%E4%B8%8A%E4%BB%A3%E7%A0%81%E3%80%82)
> 
> 我觉得还是以实际表现为准，我尽快核对一下 `uni-file-picker` 返回的参数。

十分感谢

**Comment by zhuddan** [comment]
🙏十分感谢！

**Comment by ModyQyW** [comment]
请尝试 0.5.4 :D

**Comment by zhuddan** [comment]
谢谢

**Comment by zhuddan** [comment]
想请教一下 [_UniFilePickerTempFileFile ](https://github.com/uni-helper/uni-ui-types/blob/main/src/UniFilePicker.ts#L223)的类型为什么是

```ts
interface _UniFilePickerTempFileFile extends Partial<File> {
}
```
而不是

```ts
interface _UniFilePickerTempFileFile extends File {
}
```

当是第一种情况`interface _UniFilePickerTempFileFile extends Partial<File>`时,`_UniFilePickerTempFileFile `类型就不是`File`的子类，而是`Partial<File>`的子类。按照uniapp选择文件应该是封装后调用了[uni.choosefile](https://zh.uniapp.dcloud.io/api/media/file.html#choosefile)，根据`uni.choosefile`api的`success`返回参数说明,`tempFiles`是`Array<Object>、Array<File>`，即`文件的本地文件列表，每一项是一个 File 对象`,  故`uni-file-picker`组件中选择文件之后[chooseFiles](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-file-picker/components/uni-file-picker/uni-file-picker.vue#L362)返回的`tempFiles`应该是 一个 `interface _UniFilePickerTempFileFile extends File`而不是`interface _UniFilePickerTempFileFile extends Partial<File>`

下面是我的代码
```ts

// type _UniFilePickerOnSelectEvent = {
//   /** 文件信息 */
//   tempFiles: _UniFilePickerTempFile[];
//   /** 文件临时路径 */
//   tempFilePaths: string[];
// }

// UploadFileType  即 上文中的_UniFilePickerOnSelectEvent 
type UploadFileType = Parameters<Required<UniFilePickerInstance>['onSelect']>[0];

//  UploadFileType['tempFiles'][number]['file'] 即  interface _UniFilePickerTempFileFile extends Partial<File>
function onUploadFileSingleFile(tempFile: UploadFileType['tempFiles'][number]['file']) {
  return new Promise((resolve, reject) => {
    uni.uploadFile({
      url: `${__APP_API_URL__}/common/uploadMinio`,
      file: tempFile, // <=== 没有与此调用匹配的重载。
//   第 1 个重载(共 2 个)，“(options: UploadFileOption): Promise<UploadFileSuccessCallbackResult>”，出现以下错误。
//   第 2 个重载(共 2 个)，“(options: UploadFileOption): UploadTask”，出现以下错误。ts(2769)
// uni.d.ts(251, 9): 所需类型来自属性 "file"，在此处的 "UploadFileOption" 类型上声明该属性
// uni.d.ts(251, 9): 所需类型来自属性 "file"，在此处的 "UploadFileOption" 类型上声明该属性
      name: 'file',
      header: {
        Authorization: `Bearer ${getToken()}`,
      },
    }).then((res) => {
      try {
        const responseData = JSON.parse(res.data) as ResponseResult<UploadCallback>;
        const { code, msg } = responseData;
        if (code != 200) {
          showToastError(msg!);
          reject(msg!);
        }
        else {
          const uploadSuccessFile: FileModel = {
            name: responseData.originalFilename,
            extname: responseData.extname,
            url: responseData.url,
          };
          if (model.value instanceof Array)
            model.value = [...model.value, uploadSuccessFile];
          else
            model.value = uploadSuccessFile;

          resolve(model.value);
        }
      }
      catch (error) {
        showToastError('上传失败');
        reject('上传失败!');
      }
    });
  });
}
```
上述代码可能是因为 uni app 声明报错导致的，本质上是`tempFile`的类型不是`File`而是` Partial<File>`所导致的，故意我在[源码](https://github.com/uni-helper/uni-ui-types/blob/main/src/UniFilePicker.ts#L223)处修改为`interface _UniFilePickerTempFileFile extends File {`即可解决

**Comment by ModyQyW** [comment]
@zhuddan 感谢你提出这个问题。

现在已经改掉了，0.5.5 去掉了 Partial。

一开始加上 Partial 是因为在实际测试中发现返回的数据缺少了一些 File 应有的属性，所以推测只有 H5 会返回真正的 File，其它平台只是 FileLike。

既然官方这样写类型，那我们暂且按照官方的来吧。

**Comment by zhuddan** [comment]
@ModyQyW 
很抱歉，由于我目前的开发环境主要是H5和小程序，没有考虑过app环境的实际情况，所以可能真实情况可能为FileLike。
但是现在已经去掉Partial的话还是很谢谢~至少我现在的代码不用在`uni.uploadFile`时使用 `tempFile as unknown as File`

🙏十分感谢！
