### ISSUE TITLE
uni-fab 的 pattern属性应为Partial，且pattern缺少icon属性

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-ui-types#36]
### 描述问题

`uni-fab`的`pattern`类型应该为Partial<_UniFabPattern>  [源码](https://github.com/uni-helper/uni-ui-types/blob/main/src/UniFab.ts#L94)  ,`_UniFabPattern`需要新加`icon`属性 [源码](https://github.com/uni-helper/uni-ui-types/blob/main/src/UniFab.ts#L4)
参考
```ts

type _UniFabProps = Partial<{
  /** 可选样式配置项 */
  pattern: Partial<_UniFabPattern>;
  ...
}>


interface _UniFabPattern {
 icon:_UniIconsType | _UniIconsCustomType;
 ...
}

```

关于`pattern`的`icon`属性虽然官方在[issues 710 ](https://github.com/dcloudio/uni-ui/issues/710)声称已经修复，但是我无论从插件市场下载uni-ui 、使用npm下载的@dcloudio/uni-ui或者使用hbuilder创建新的uni-ui模板项目中的源代码中，[都没有修复](https://github.com/dcloudio/uni-ui/issues/710#issuecomment-1489878495)

### 复现

```vue
    <uni-fab :pattern="{ iconColor: 'red' }" /> // 类型“{ iconColor: string; }”缺少类型“_UniFabPattern”中的以下属性: color, selectedColor, backgroundColor, buttonColorts(2739)
    <uni-fab :pattern="{ icon: 'color' }" /> //不能将类型“{ icon: string; }”分配给类型“_UniFabPattern”。
  对象字面量只能指定已知属性，并且“icon”不在类型“_UniFabPattern”中。
```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 4.35 GB / 15.73 GB
  Binaries:
    Node: 14.21.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 6.14.18 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54), ChromiumDev (112.0.1722.23)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
万分感谢🙏

修复了，晚点和 #35 一起发布

**Comment by zhuddan** [comment]
> 万分感谢🙏
> 
> 修复了，晚点和 #35 一起发布

🙏十分感谢！
