### ISSUE TITLE
_UniDataPickerLocaldataItem类型错误

### ISSUE THREAD

**Issue by LiZhequ** [uni-helper/uni-ui-types#43]
### 描述问题

_UniDataPickerLocaldataItem 类型中，selected为非必填，应为可选属性，由于可以通过map来配置value和text的映射，value和text也应该为可选属性 @

### 复现

localdata数组项无value，text或selected属性时报类型错误

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 5.78 GB / 15.34 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
    Internet Explorer: 11.0.19041.1202
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
linked
- https://uniapp.dcloud.net.cn/component/uniui/uni-data-picker.html#api
- https://gitee.com/dcloud/datacom
- https://gitee.com/dcloud/datacom/blob/master/tree.schema.json
- https://gitee.com/dcloud/datacom/blob/master/array.schema.json
