### ISSUE TITLE
uni-tag 组件 props custom-style 不支持 string 

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-ui-types#44]
### 描述问题

uni-tag 标签custom-style应该支持 `string` 或者 [CSSProperties](https://vuejs.org/api/utility-types.html#cssproperties)(不应该是[_AnyRecord](https://github.com/uni-helper/uni-ui-types/blob/main/src/UniTag.ts#L30))

[官网示例](https://zh.uniapp.dcloud.io/component/uniui/uni-tag.html#%E7%A4%BA%E4%BE%8B)使用的`string`

虽然[源码](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-tag/components/uni-tag/uni-tag.vue#LL66C4-L66C15)定义的类型是String, 但是[CustomStyle](https://github.com/dcloudio/uni-ui/blob/master/uni_modules/uni-tag/components/uni-tag/uni-tag.vue#L2)的绑定是vue的Style绑定方式, 故应该支持 string 或者 CSSProperties

### 复现

以下两种方式均可以正常工作，但是使用 string 类型会报错

```vue
 <uni-tag
  :custom-style="{ color: '#4335d6' }"
  text="test"
  ></uni-tag>

  <uni-tag
    custom-style="color:#4335d6" //不能将类型  分配给类型“_AnyRecord”。
    text="test"
  ></uni-tag>
```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 1.72 GB / 15.73 GB
  Binaries:
    Node: 16.19.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.35), ChromiumDev (115.0.1843.0)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by zhuddan** [comment]
使用对象可以ts类型正常工作，但是源码中的类型是String 还是会导致vue警告
[Vue warn]: Invalid prop: type check failed for prop "customStyle". Expected String with value "[object Object]", got Object  
  at <UniTag inverted=true size="small" custom-style= {color: "#4F4A66"}  ... > 
  at <SwiperCalendar list= (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}] date="2023-05-10" > 
  at <Index >




所以还是建议修改成 string把

 ```ts
/** 自定义样式 */
type _UniTagCustomStyle = string;
```

**Comment by ModyQyW** [comment]
Fixed in 0.5.10. Thanks a lot! 🙏
