### ISSUE TITLE
The input parameters for forms rules and forms item rules are different, but the types are the same 

### ISSUE THREAD

**Issue by xue-lei** [uni-helper/uni-ui-types#48]
### 描述问题

forms item rules is an array，not a key value

### 复现
```
<uni-forms-item
          label="上传文件命名"
          :rules="[{required: true,errorMessage: '上传文件命名不能为空'}]"
          :name="['irBaseFileInfo', 'fileName']">
          <uni-easyinput
            v-model="fileUploadInfo.irBaseFileInfo.fileName"
            type="textarea"
            auto-height
            :input-border="false"
            :clearable="false"/>
        </uni-forms-item>

```

### 系统信息

```Shell
uniapp and types all latest
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
很抱歉，最近个人事务繁忙，暂时没有时间来处理这个 issue。如果可以的话，欢迎提交 PR，或请耐心等待，谢谢 🙏
