### ISSUE TITLE
@dcloudio/uni-app 引入错误

### ISSUE THREAD

**Issue by sishen654** [uni-helper/uni-ui-types#51]
### 描述问题

关于 @dcloudio/uni-app 的引入错误：
![image](https://github.com/uni-helper/uni-ui-types/assets/65691266/be7d5fed-410e-4c41-a523-b871d20060c8)

tsconfig 是正确配置的：
![image](https://github.com/uni-helper/uni-ui-types/assets/65691266/1e6ecb39-74fe-4a51-a51d-c35bff1f394d)

### 复现

这个是当前仓库中的 playground 中显示的，我在其他 uniapp 项目遇到一样的问题

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 2.55 GB / 15.72 GB
  Binaries:
    Node: 16.20.2 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nodejs\yarn.CMD
    npm: 8.19.4 - D:\nodejs\npm.CMD
    pnpm: 8.6.12 - D:\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1
Volar: 1.8.8
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
<img width="1024" alt="image" src="https://github.com/uni-helper/uni-ui-types/assets/31850793/e6a900d9-bb7f-408d-92e2-47fb43284c3c">
看你的截图，似乎没有安装依赖

**Comment by sishen654** [comment]
> <img alt="image" width="1024" src="https://user-images.githubusercontent.com/31850793/265907640-e6a900d9-bb7f-408d-92e2-47fb43284c3c.png"> 看你的截图，似乎没有安装依赖

我试试哈
