### ISSUE TITLE
组件uni-calendar的props selected TS类型错误

### ISSUE THREAD

**Issue by dhanweb** [uni-helper/uni-ui-types#57]
### 描述问题

selected应该为一个数组，但是它的TS提示为对象，并且data属性应该为非必选
![image](https://github.com/uni-helper/uni-ui-types/assets/105217481/1eecf7bf-10b7-4bef-8581-47e3aa55c330)

### 复现

```
<uni-calendar
   :selected="dateData"
 />
const dateData = ref([
  {
    date: '2024-3-15',
    info: '158.21',
  },
```
此时`selected`会提示不能将类型“{ date: string; info: string; }[]”分配给类型“_UniCalendarSelectedElement”。ts-plugin(2322)

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 7.62 GB / 31.69 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\Volta\tools\image\node\18.19.0\node.EXE
    npm: 10.2.3 - ~\AppData\Local\Volta\tools\image\node\18.19.0\npm.CMD
    pnpm: 8.15.3 - C:\Program Files\Volta\pnpm.EXE
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
1. 我这里TS提示为数组，是缺少了 data 这个属性

Type '{ date: string; info: string; }[]' is not assignable to type '_UniCalendarSelectedElement[]'.ts-plugin(2322)

2. 你的复现没复制全

**Comment by ModyQyW** [comment]
0.5.13 将 data 设为了可选
