### ISSUE TITLE
看了使用说明，意思是需要手动导入类型然后赋值类型吗？那岂不是太麻烦了，用到的都要指定一遍

### ISSUE THREAD

**Issue by spriteApe** [uni-helper/uni-ui-types#59]
### 对问题的清晰和简明的描述

看了使用说明，意思是需要手动导入类型然后赋值类型吗？那岂不是太麻烦了，用到的都要指定一遍

### 推荐的解决方案

期望下载这个包，作为一个uni-ui的类型补充说明，就像@types/lodash这个包一样

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by Skiyee** [comment]
我试着理解该issue所表达的含义，如果你是希望能够自动推导出所使用的类型的话，目前该仓库是无法做到的

如果你有好的主意并且能够实现 `PR welcome 🤗`

**Comment by ModyQyW** [comment]
把【uni-ui 组件类型】和【lodash 方法类型】两个场景放在一起比较不合适，况且你可以在 template 里面直接写 method，但无论如何都是存在着部分限制。有更好的实现欢迎提出讨论和提交 PR。
