### ISSUE TITLE
Volar版本大于等于v2.0.22时，uni-ui组件类型在template中显示为unknown

### ISSUE THREAD

**Issue by hexiaobang** [uni-helper/uni-ui-types#60]
### 描述问题

问题：Volar版本大于等于v2.0.22时，uni-ui组件类型在template中显示为unknown
描述：已严格按照文档要求进行配置，问题如上所述

### 复现

@uni-helper/uni-ui-types版本 -> 0.5.11
volar版本 >= v2.0.22

### 系统信息

基础环境信息:
  - os: `macOS 14.5`
  - node: `18.18.2`
  - packageManager: `pnpm`
  - vscode: `1.90.2`
  - volar: `2.0.22`

基础依赖信息:
  - vue: `3.4.23`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-alpha-4010520240507001`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
https://github.com/vuejs/language-tools/issues/4501

**Comment by ModyQyW** [comment]
如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21

**Comment by hexiaobang** [comment]
> 如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21

我用的这条解决方案，感觉不错 ⬇️
`type A = import('@vue/runtime-core').GlobalComponents;

declare module 'vue' {
  interface GlobalComponents extends A {}
}`

**Comment by hexiaobang** [comment]
> 如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21

感谢，我目前在用这条解决方案，感觉不错 ⬇️
```
type A = import('@vue/runtime-core').GlobalComponents;

declare module 'vue' {
     interface GlobalComponents extends A {}
}
```

**Comment by mxp131011** [comment]
Volar版本大于等于v2.0.28时,所有都无效了

**Comment by ModyQyW** [comment]
> [vuejs/language-tools#4501](https://github.com/vuejs/language-tools/issues/4501)

还在等官方回复

**Comment by ModyQyW** [comment]
我即将归档这个仓库并将工作迁移到 [@uni-helper/uni-types](https://github.com/uni-helper/uni-types) 中继续进行
